<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>hola</h1>
        <div>a microframework for PHP</div>

        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p>Try <a href="http://www.slimframework.com">SlimFramework</a></p>
        <?php endif; ?>
    </body>
    
    <div class="jumbotron jumbotron-red">
    <div class="container">
        <h1>Search</h1>
        <p class="lead">Here are the results for <code><?php echo htmlspecialchars($query); ?></code></p>
    </div>
</div>
<div class="container container-numphp">
    <?php foreach($results as $key => $result): ?>
        <h2 class="page-header"><?php echo $key; ?></h2>
        <?php foreach($result as $entry): ?>
            <h3>
                <a href="<?php echo $entry['uri']; ?>" title="<?php echo $entry['title']; ?>"><?php echo $entry['title']; ?></a>
            </h3>
        <?php endforeach; ?>
    <?php endforeach; ?>
</div>

</html>
